### ISSUE TITLE
code review: milestone 2

### ISSUE THREAD

**Issue by murmurise** [summerchenxy/CrazyAuction#2]
1. use variable name password instead of pw as a short form, any short form is rarely used in all lecture sample codes so far. In case you are worried about typo a long variable name, you can use command+K (for Mac. it should be something like Ctrl+K for Windows) to auto-complete the name.  Also, you should be able to use refractor to auto-populate the changed variable name.
2.  Auction(Listing)Type (enum) is needed 

3. **<employee controller>**
- employeeLogin() method: you can merge the two InvalidLoginCredentialException into one. Alternatively, you can pass in different message String 

-changePw(): change method naming 

- createNewEmployes(): missing refresh()
-deleteEmployee: you may want to flush() after remove (see:http://lnr.li/r9ndx)

4. I have added some attributes to CreditPackage Entity Class along with constructors and getter&setter. please check it out.
5. I notice you have not completed the relationship mapping(employee & credit package). Please don't forget to do so (and update getter&setter 🤓 )
6. having said 5, I am not sure if there is even a relationship between the two.

**Comment by summerchenxy** [comment]
1. Bid: pls add relationship for bid with credit package, auction listing, credittxn
2. Customer: is Collection better than List? Curious to know why use Collection<Address> rather than List
3. CreditTxn: i added false optional for credittxn n customer. for package im not sure. Prof's UML says 0..1 ie optional. but how is it possible to have a transaction without a credit package? pls add relationship between txn n Bid (not sure)
4. CreditPackage: pls add relationship between package n Bid (not sure)
5. Address:
6. general:
6.1 not sure when to use identity or when to use auto. 
6.2 not sure what to set for the length of column
6.3 joinColumn
6.4 command prompt or ui
6.5 rebase

**Comment by summerchenxy** [comment]
1. Bid: pls add relationship for bid with credit package, auction listing, credittxn
2. Customer: is Collection better than List? Curious to know why use Collection rather than List
3. CreditTxn: i added false optional for credittxn n customer. for package im not sure. Prof's UML says 0..1 ie optional. but how is it possible to have a transaction without a credit package? pls add relationship between txn n Bid (not sure)
4. CreditPackage: pls add relationship between package n Bid (not sure)
5. Address: 
6. general:
6.1 not sure when to use identity or when to use auto.
6.2 not sure what to set for the length of column
6.3 joinColumn
6.4 command prompt or ui
6.5 rebase

**Comment by summerchenxy** [comment]
my part: 
logout in controller or just in client?
same for change password

**Comment by murmurise** [comment]
1. bid - credit package; bid - auction listing; I don't think there is relationship between creditTransation and bid, since creditTransaction are records of customers buying credit packages.
2. I don thtink we need to use an ordered Collection (i.e. List) for addresses or credit transaction history... but they are both instantiated as arraylist (which can be indexed), so i supposed it does not really matter.. will ask prof about this! (ref: https://stackoverflow.com/a/3317395)
3. What's  false optional? A transaction with no credit package could be when a "dummy" transaction is created to keep some record? say the system want to note down that the customer changed address or something. ( but that implies there should be an option String to take note of such event).
4. ref to 1.
5.
6. (in person)

**Comment by murmurise** [comment]
ask the prof 
- collection vs list
- credittxn without creditpkg

**Comment by murmurise** [comment]
bid - credit package rlts, bid - auction listing, bit - creditTxn rlts added

**Comment by murmurise** [comment]
question to prof: What is the difference between 'optional = false' on the @ManyToOne annotation and 'nullable = false' on the @JoinColumn annotation? is setting both of them redundant?

**Comment by summerchenxy** [comment]
question to prof: What is the difference between 'optional = false' on the @manytoone annotation and 'nullable = false' on the @joincolumn annotation? is setting both of them redundant?
entity in ejb or lib
